### ISSUE TITLE
Extracting generic bits in a common library

### ISSUE THREAD

**Issue by jeluard** [stephenmuss/argo#1]
Great work on argo!

I am also interested in having JSON API support in Clojure world. I was thinking it would be nice to have a simple library that would provide common function implementation (errors, link abstraction, pagination , sparse fields syntax, ..)
That library could be useful for server and clients and could be available on Clojure(Script).

It looks like some relevant bits could be extracted from argo. What do you think?

**Comment by stephenmuss** [comment]
Sure, I am open to that. Which bits did you have in mind specifically?

**Comment by jeluard** [comment]
The pagination code and error handling looks great candidates. Sparse fields might too but it looks like `argo` doesn't support them yet? BTW what client do you use to consume JSON API?

I will start working on something and let you know about my advances. It might take some time.

**Comment by stephenmuss** [comment]
Yeah, I didn't bake in sparse fieldsets as I thought that could be left as an exercise for those using Argo.

As for clients I haven't really used any JSON API specific ones.

Looking forward to seeing what you come up with. Cheers.
