### ISSUE TITLE
Pedestal

### ISSUE THREAD

**Issue by afhammad** [stephenmuss/argo#4]
Reading through the Readme and example source code, the implementation looks simple enough, good job on that front. I dug into the library code and noticed it's tightly coupled with ring & compojure. 

Do you think it would be difficult to support pedestal?

**Comment by stephenmuss** [comment]
I can't really envision how that would work right now. As you mention, argo is currently built on top of ring and compojure.

I'm open to discussing options if you have any ideas.

**Comment by afhammad** [comment]
Thanks i'll look into it and get back to you!
